### ISSUE TITLE
Q: How to convert proposerAddress back to bech32

### ISSUE THREAD

**Issue by npow** [cosmos/cosmjs#1016]
I am trying to convert the `proposerAddress` back to bech32 format, but when I do so it doesn't match the validator address showing up on mintscan.

```
  const tendermintClient = await StargateClient.connect('https://osmosis-1.technofractal.com/');
  const res = await tendermintClient.tmClient.block(2956000);
  const string = Bech32.encode("osmo", res.block.header.proposerAddress);
  console.log(string);
```
This outputs: `osmo1arm6ztth2njxndd2cwpg6gt6q79wdfyf26rnjx`, while on [mintscan](https://www.mintscan.io/osmosis/blocks/2956000) it shows the proposer as [Nascent](https://www.mintscan.io/osmosis/validators/osmovaloper1gxlsy3jmt5aevkmlfh7rnnxrtqzqe4a65vr776) which has address `osmo1gxlsy3jmt5aevkmlfh7rnnxrtqzqe4a6wmtafa`. The address I encoded has no tokens either, so I must be doing something wrong.

**Comment by webmaster128** [comment]
The proposer address you get from the Tendermint client is derived from an ed25519 Tendermint consensus keypair. Those are the addresses that have "cons" in their prefix.

You cannot interact with this address on the application level directly. This is why fancy browsers map it to the Cosmos SDK app level addresses for the users because they know both addresses of a validator.

I **think** you can do the mapping through the /staking/validators list (e.g. https://lcd-osmosis.blockapsis.com/staking/validators) by deriving the Tendermint address from `consensus_pubkey` using `pubkeyToAddress` from `@cosmjs/tendermint-rpc`. You might find a better query API for doing the mapping in [packages/stargate/src/queries/staking.ts](https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/queries/staking.ts).

**Comment by webmaster128** [comment]
Here is a full example how to do the mapping via the staking.validators query: https://github.com/noislabs/proposers/blob/f552cf24724f8ab719168a149c7e3109b7606d37/index.ts. The core to produce the mapping from proposer address to operator are those lines: https://github.com/noislabs/proposers/blob/f552cf24724f8ab719168a149c7e3109b7606d37/index.ts#L34-L48
