### ISSUE TITLE
Add authz and feegrant messages to default types

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#1026]
authz and feegrant [were](https://github.com/confio/cosmjs-types/pull/17) [added](https://github.com/confio/cosmjs-types/pull/26) to the code generator already. They add the new message types:
- cosmos.authz.v1beta1.MsgGrant
- cosmos.authz.v1beta1.MsgExec
- cosmos.authz.v1beta1.MsgRevoke
- cosmos.feegrant.v1beta1.MsgGrantAllowance
- cosmos.feegrant.v1beta1.MsgRevokeAllowance

They should be added to the Stargate registry.

For the AminoTypes it seems like no Amino JSON signing is implemented on-chain. So we should create a specific error message for that, explaining why it does not work.

**Comment by webmaster128** [comment]
This should make https://github.com/cosmos/composer/blob/master/react/src/redux/action-creator/wallet.ts#L59-L60 unnecessary.

**Comment by webmaster128** [comment]
Reopening because this part is missing:

> we should create a specific error message for that, explaining why it does not work.

We should add an implementation to https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/aminotypes.ts#L67-L511 for the new message types where both `toAmino` and `fromAmino` are implemented by throwing this error: "This message type cannot be signed using the Amino JSON sign mode because this is not implemented on-chain."

**Comment by msteiner96** [comment]
I added the error in #1039 , but wonder how I should do the `fromAmino()` , what's the aminoType of those new added protobuf urls? @webmaster128

**Comment by crypzoh** [comment]
I have a question around the not implemented aminoTypes. That also means, that signing those kind of messages won't work with a ledger device, since it seems that when using a ledger it requires the amino signer?

**Comment by RiccardoM** [comment]
All right, I've tested some things and it seems possible to do it, as long as CosmJS allows for **truly** custom encoding/decoding when using Amino. 

#### Context
Currently `x/authz` messages **do** support Amino encoding, but in a very custom way. They don't have the classic JSON message structure (with the `type` and `value` field), and instead they put the `value` as the entire JSON object. 

Instead of having something like this: 
```json
{
  "type": "cosmos/MsgGrant",
  "value": {
    "grant":{
      "authorization":{},
      "expiration":"2023-02-17T15:37:29Z"
    },
    "grantee":"desmos1gedewhj0qpm55yc359e6qd36wkl9jvnp3zk90h",
    "granter":"desmos1vxe0qadrgpg52zk03k5r29wd9jt59ej664t2yl"
  }
}
```

We have something like this: 
```json
{
  "grant":{
    "authorization":{},
    "expiration":"2023-02-17T15:37:29Z"
  },
  "grantee":"desmos1gedewhj0qpm55yc359e6qd36wkl9jvnp3zk90h",
  "granter":"desmos1vxe0qadrgpg52zk03k5r29wd9jt59ej664t2yl"
}
```

#### Possible solution
Once possible solution is to define the following converter: 

```ts
export const cosmosTypes: Record<string, AminoConverter> = {
  // Authz types
  "/cosmos.authz.v1beta1.MsgGrant": {
    aminoType: "",
    toAmino: (value: MsgGrant): AminoMsgGrant => {
      return {
        grant: value.grant ? convertGrant(value.grant) : undefined,
        granter: value.granter,
        grantee: value.grantee,
      };
    },
    fromAmino: (msg: AminoMsgGrant): MsgGrant => {
      return MsgGrant.fromPartial({
        grant: msg.grant ? convertAminoGrant(msg.grant) : undefined,
        granter: msg.granter,
        grantee: msg.grantee,
      });
    },
  },
};
```

The problem with this is that (after testing it), I've found out that CosmJS automatically puts everything that is returned here inside the `value` object, and then uses the specified `aminoType` as the `type` field value. 

I think that by applying the following changes to CosmJS everything could be implemented properly: 
1. allow `aminoType` to be undefined (or a custom type explicitly telling that this is a custom encoding - maybe something like `Exclude` or else)
2. during the encoding, if the `aminoType` value is saying the encoding should be custom, **do not** build the default `{ "type": "", "value: {} }` object. Instead, use the value returned by the `toAmino` as the entire JSON object to be used.

**Comment by amaurym** [comment]
If I'm not mistaken, the reason we have weird amino encoding for authz/feegrant is because we forgot to add the [`RegisterLegacyAminoCodec`](https://github.com/cosmos/cosmos-sdk/blob/9ce0844847cd3a6b2dc181cab21af319ceb95d05/x/bank/types/codec.go#L14) function.

We can definitely add RegisterLegacyAminoCodec for authz/feegrant in v0.46. But CosmJS must detect the SDK version, and throw an error for <0.46.

**Comment by nooomski** [comment]
Ah, there you go. Great timing. Are you okay to create an issue on the SDK @amaurym ?

**Comment by webmaster128** [comment]
I would appreciate a solution that is consistent with the current Amino JSON framework. The lack of a type identifier makes it impossibe to do the reverse conversion (Amino JSON -> proto) and would requires us to change a lot of architecture and probably break caller code.

**Comment by amaurym** [comment]
We can track this issue on the SDK here: https://github.com/cosmos/cosmos-sdk/issues/11190. There's also a draft PR https://github.com/cosmos/cosmos-sdk/pull/11214.

**Comment by webmaster128** [comment]
> Note that this will be only available starting on v0.46.

That's fine with me. CosmJS users can change the configuration of the `AminoTypes` class in their application to adapt it to their backend. And then at some point the authz messages just get integrated by default assuming a 0.46+ backend. Then they can still be overriden by 0.45 projects.

For now we'll just change the term "not implemented on chain" to "not supported on chain" in #1039 and consider a non-compliant implementation "not supported".

**Comment by webmaster128** [comment]
By the way, @amaurym, thank you for implementing Amino JSON sign mode for the new types. I have the impression this will make many people very happy and help the adotion of the new functionality.

**Comment by webmaster128** [comment]
This discussion has been summarized in https://medium.com/confio/authz-and-ledger-signing-an-executive-summary-8754a0dc2a88 in order to educate the various stakeholder. The follow-up ticket is https://github.com/cosmos/cosmjs/issues/1092.
