### ISSUE TITLE
Question on Submitting a custom msg type generated from stargate

### ISSUE THREAD

**Issue by ankur325** [cosmos/cosmjs#1073]
When I try to submit a custom msg, cosmjs API tries to get the account details by using the default QueryClientImpl which uses the following code

```Account(request) {
        const data = exports.QueryAccountRequest.encode(request).finish();
        const promise = this.rpc.request("cosmos.auth.v1beta1.Query", "Account", data);
        return promise.then((data) => exports.QueryAccountResponse.decode(new minimal_1.default.Reader(data)));
    }```  

How can I associate my own request for getting account instead of "cosmos.auth.v1beta1.Query", "Account"

**Comment by webmaster128** [comment]
Why would you want to do that?

I assume you use signAndBroadcast or something like that, which under the hood queries account number, sequence and chain ID.

**Comment by ankur325** [comment]
Yes.. We do call signandbroadcast which is what gets called from the vurx actions js files generated by starport build. Our account is custom so was trying to not re-write entirely

**Comment by webmaster128** [comment]
I.e. you need a custom response encoding here? https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/accounts.ts#L44-L84 Or you don't have the default query at all?

**Comment by ankur325** [comment]
You are right.. there is no default query itself.. there is a different query that returns a type that implements IAccount interface

**Comment by webmaster128** [comment]
Why do you not implement the default query?

**Comment by ankur325** [comment]
We had our own Auth module, and the query path is custom not the default cosmos. I guess I am out of luck here :-)

**Comment by webmaster128** [comment]
In #1071 you see initial effort to organize the code in a way that is much more aligned with the Cosmos SDK module system. For now it only moves files and symbols around but mid term it will become much easier to assemble your own high level client when looking at the `SigningStargateClient` as an example. However, for now I don't see us modifying `SigningStargateClient` in a way that makes such core components that have great acceptance across chains swapable. So your best bet is probably a clone of `SigningStargateClient`/`StargateClient` which uses lower level CosmJS components as a dependency but is otherwise maintained by you for your chain.

**Comment by ankur325** [comment]
Thanks .. appreciate your insights. I am closing the ticket
