### ISSUE TITLE
Question: Atomic transfers

### ISSUE THREAD

**Issue by dimitardanailov** [cosmos/cosmjs#1141]
Greetings,

I'd like to ask if cosmosjs supports: Atomic transfers
I've experience with Algorand. Algorand supports Atomic transfers

![atomic_transfers-1](https://user-images.githubusercontent.com/2182018/166893925-34c21ed2-4888-43f2-a7ef-5f8af9b02632.png)

Documentation: 
https://developer.algorand.org/docs/get-details/atomic_transfers/

SDK method:
https://developer.algorand.org/docs/get-details/atomic_transfers/

I'd like to receive more details about this subject.

**Comment by webmaster128** [comment]
This is possible in Cosmos SDK using so called messages. Each message is an instruction for an action. A basic example is MsgSend for sending tokens. You can have 3 of those in a transaction that is then signed by 3 signers where each signer is the sender of some coins.

This was implemented before the Stargate upgrade in CosmJS. We currently don't have an implementation for that due to the lack of interest from users.

**Comment by dimitardanailov** [comment]
@webmaster128: nice to meet you! 
Thank you very much for the answer! Your answer gave me insperation to try a new approach and the final result is: https://cosmoshub-testnet.mintscan.io/cosmoshub-testnet/txs/4BC832DA2C364FEF8A75C6D94002588A428BD7F26253FA601BF08E737F0B4BF0

What's the benefit if we group the transactions ?

**Comment by webmaster128** [comment]
The transaction looks good. That's the Cosmos way to do this: one transaction with multiple messages.

Now as long as all 3 message have the same "From Address", only this account has to sign the transaction. If you have different Froms, all need to sign the transaction.

> What's the benefit if we group the transactions ?

Could you elaborate what you mean by that?

**Comment by dimitardanailov** [comment]
Greetings, 

> If you have different Froms, all need to sign the transaction.
I've a question: How to sign the transaction for each different address ? 

> What's the benefit if we group the transactions ?
What's is the difference if we make three different transactions or one transaaction like: https://cosmoshub-testnet.mintscan.io/cosmoshub-testnet/txs/4BC832DA2C364FEF8A75C6D94002588A428BD7F26253FA601BF08E737F0B4BF0

**Comment by nooomski** [comment]
The benefit is generally a UX improvement, applications might want to perform multiple actions and only have the wallet owner sign one transaction instead of multiple ones.
The atomic transaction you have listed above isn't supported in CosmJS at the moment because currently there aren't clearly defined uses cases that require us to prioritize this feature.

**Comment by webmaster128** [comment]
Is there anything else we can do here? Seems like good to close if you don't have follow-up questions or want to convince us that atomic transactions with multiple signers are needed.
