### ISSUE TITLE
BigInt for block height

### ISSUE THREAD

**Issue by kriskowal** [cosmos/cosmjs#1263]
Tendermint and Stargate pretty consistently provide `number` -typed block height, though the Go range for block heights is in the 64 bit range. The JSON RPC APIs also use numbers, as opposed to strings. I see that there’s been some motion toward using bigints where appropriate. Is there a possibility block height will move to bigint in memory and decimal string on the wire?

**Comment by webmaster128** [comment]
We use number for heights because that's the most convenient thing to use for JS devs. And I don't expect heights greater than the safe integer range.

**Comment by kriskowal** [comment]
Thanks for the clarification. (I’ll be sure to reach out again in a billion years 😉)

**Comment by webmaster128** [comment]
The overall sentiment is: what we get from the chain (both Tendermint RPC and Cosmos SDK LCD APIs) has historically been incredibly inconsistent due to the lack of API design. We got numbers, strings, empty strings, "0" strings, omitted fields – changing in patch releases. We try to shield the users from this and provide a type that is convenient to use in JS/TS applications. Especially with heights I do a bit of math (`+ 1`, `h1 < h2` and such things).

I think there is not good solution to serve all needs. `number` is a safe range < 64 bit, I don't like the long library, we created Uint64 in CosmJS which is good for low level encoding code but not convenient for app level code, BigInt [still causes trouble for React Native users](https://github.com/cosmos/cosmjs/issues/1144) and TypeScript does not allow me to use the `123n` literals. So yeah, it's a pain. Let me know if there is a specific place where the chosen type causes issues.
