### ISSUE TITLE
First-class multi-sig support

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#416]
## Step 1: Decide on implementation

We can choose between
1. off-chain authorization aggregation (multiple signatures on one transaction) or
2. on-chain authorization aggregation (multiple independent transactions to trigger an action).

## 1. off-chain authorization aggregation

**Advantages:** compatibility with [the Comos multisig ](https://hub.cosmos.network/master/resources/gaiacli.html#multisig-transactions) method (multiple pubkey squeezed into one multisig "pubkey")
**Disadvantages:** sequence numbers must not change during the signing process (i.e. a user that signed must not broadcast a different transaction until the multisig transaction is comitted); starting with Stargate, the signing mode must be coordinated before composing the transaction; off-chain infrastructure requires to aggregate the signatures.

## 2. on-chain authorization aggregation

**Advantages:** signing process is independent (one single signature tx per authorization); can be implemented nicely in wallets that track the authorization state
**Disadvantages:** higher fees due to multiple transactions; not yet standardized as far as I know

Option 2. can either be implemented using groups accounts (do they exist yet?) or CosmWasm.

## Step 2: Implement

**Comment by ethanfrey** [comment]
I would aim for Option 2 - doing on-chain aggregation.

This is both more flexible and likely to be more supported once groups or CosmWasm are enabled on a chain. Option 1 seems more legacy, and even after 1.5 years, there is no better way to aggregate these sigs than a cli and sending files over telegram

**Comment by webmaster128** [comment]
On-chain authorization aggregation it is. Blocked by implementing a multisig contract now.

**Comment by ethanfrey** [comment]
https://github.com/CosmWasm/cosmwasm-plus/tree/master/contracts/cw3-fixed-multisig has been implemented for a few weeks now. You can use that implementation to develop multisig. The [cw3 spec](https://github.com/CosmWasm/cosmwasm-plus/tree/master/packages/cw3) is fixed (unless you raise issues with it), and I will be adding more complex implementations for it with different init/admin features, but the actual propose/vote/execute logic (using the multisig) will remain the same.

**Unblocked**

**Comment by ethanfrey** [comment]
There was request for clarification before you can start on this. I will make an attempt to clarify and please ask questions of what is still poorly defined:

We want a high-level interface for using multisigs. Right now, we focus on the "on-chain aggregation" approach, using cosmwasm cw3 contracts. We should be able to expose a similar (or identical) API backed by sdk "group module" if/when that is implemented (but providing a very similar UX). We should be able to eventually design a "off-line signature aggregation" process inspired by this work.

Ideal User flow (wallet) - submission:

* Enter a multisig address and "assume identity" (wallet checks if you are a member)
* When using an app, show all queries as the multisig
* When hitting eg. "send tokens" or "buy name" in a dApp, instead of signing the tx directly, this should trigger a "multisig proposal"
* Ideally this should require no changes to the calling app (and handled transparently in some pre-signing processor), in practice it may require a different format, but should be easy for an dApp to support both. 

User flow - approval:

* Enter a multisig address and view current open proposals
* Click on a proposal to see what was going to be signed along with an (optional) reason/note
* Easy approve/reject/execute interface

Note: adding subkey support may be a simpler (but related) workflow that should fit in the same icf milestone and may be a good way to get started here.

----

For code flow and the lower-level API we want to wrap, please refer to the [cw3 spec](https://github.com/CosmWasm/cosmwasm-plus/tree/master/packages/cw3). That should be considered in draft form, so if you want to modify this API in order to provide better UX, please add issues on cosmwasm-plus for that.
