### ISSUE TITLE
Research: Can we use OfflineSigner for Stargate?

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#479]
Can we use the existing OfflineSigner interface for Stargate transactions?
- If yes, great, done.
- If no, can we adjust it slightly to only need one interface for Launchpad and Stargate?
- If yes, great, let's do that.
- If no, create a similar interfce for Stargate

**Comment by ethanfrey** [comment]
One point that is likely different is the concept of "SignMode". Currently DIRECT (what we support in software) or LEGACY (amino-style, which the ledger uses).

This must be selected by the Signer (most implementations only support one), and both formats should be able to be derived from the TxInfo (which is slightly different than launchpad I think). One catch is that, especially in multisig, the desired signing mode of all parties needs to be specified BEFORE anyone can sign.

Thus, I would propose a second method like `signMode() -> string` that returns the sign mode the `OfflineSigner` implementation uses. This can be queried (from all signers) to properly build the TxInfo bytes. Then, they can just sign using the same algorithm. Different signers can use either algorithm. Ledger support demands this and is a good case to ensure we can get this proper.

**Comment by ethanfrey** [comment]
It is good to look at the TxInfo from stargate, not sure if that can be unified with launchpad signing

**Comment by willclarktech** [comment]
Our current `OfflineSigner` has a `sign` method with this signature:
```ts
readonly sign: (signerAddress: string, signDoc: StdSignDoc) => Promise<SignResponse>;
```
where a `StdSignDoc` is:
```ts
interface StdSignDoc {
  readonly chain_id: string;
  readonly account_number: string;
  readonly sequence: string;
  readonly fee: StdFee;
  readonly msgs: readonly Msg[];
  readonly memo: string;
}
```
In order to support `SIGN_MODE_DIRECT` using the existing interface, we need the following in order to generate a `Uint8Array` representation of a transaction:
- `chainId` (same as `chain_id` in `StdSignDoc`)
- `accountNumber` (equivalent to `account_number` in `StdSignDoc`)
- `txBody` requires
  - `memo` (same as `memo` in `StdSignDoc`)
  - `msgs` which are equivalent to `msgs` in `StdSignDoc` but would need to be converted, in particular to swap the Amino `type` field for a `typeUrl` field
- `authInfo` requires
  - `sequence` (equivalent to `sequence` in `StdSignDoc`)
  - `feeAmount` and `gasLimit` (equivalent to `fee` in `StdSignDoc`)
  - `pubkeys` which should be known by the signer given the `signerAddress`

So it's possible to keep the existing interface. The cost is continuing to support/promote the Amino-friendly `Msg` format, and convert back and forth a lot. It's also unclear whether we'll continue to be able to use this interface with future sign modes (see https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-020-protobuf-transaction-encoding.md#future-improvements).

As a result I propose (in https://github.com/cosmos/cosmjs/pull/482) adjusting the `sign` method type signature to accept a "sign job", which specifies the sign mode as well as the content to be signed. We can require signers to expose a `signModes` property which lists sign modes supported by the signer (a list rather than a string in case signers support multiple modes). We also future-proof ourselves against the expected additional sign modes like `SIGN_MODE_TEXTUAL`.
