### ISSUE TITLE
Auto-calculate TokenInfo

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#50]
One of the biggest config issues is the array of TokenInfo needed to properly handle the chain in `CosmWasmConnection`. We can query `supply` for a list of all denoms on the chain. Then auto-generate TokenInfo as follows:

* if denom starts with "u": ticker = `drop "u", convert to uppercase`, fractionalDigits = 6
* else: ticker = `convert to uppercase`, fractionalDigits = 0

We can allow a TickerInfo override that will replace any auto-generated info, but this means for many test chains, we can get away without any config here, and make life easier when integrating.

**Comment by webmaster128** [comment]
Any kind of automation depends on the implementation of [ADR 024: Coin Metadata](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-024-coin-metadata.md).

**Comment by webmaster128** [comment]
Closing since TokenInfo does not exist anymore in CosmJS. App developers are now responsible for finding a representation of a amount/denom pair that is intuitive depending on the use case. This can be done by hardcoding supported tokens or using ADR 024: Coin Metadata. The `Decimal` class from `@cosmjs/math` make this easy.
