### ISSUE TITLE
Failing check for stargate testnet

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmjs#537]
https://github.com/cosmos/cosmjs/blob/19e47d3e2f6838475698808f87ee5d61aaa45f80/packages/launchpad/src/lcdapi/auth.ts#L71

The account type is now `cosmos-sdk/BaseAccount` but there are also vesting accounts with different types. I recommend removing this check to be better compatible with a broader range of networks.

**Comment by webmaster128** [comment]
Are you trying to connect to a Cosmos SDK 0.40 network using @cosmjs/launchpad? This is not supported. @cosmjs/launchpad supports 0.37–0.39 at the moment and will drop 0.37 and 0.38 once the Cosmos Hub upgraded to stargate.

In order to interact with a stargate network, the functionality from @cosmjs/stargate should be used, connecting to the chain via Tendermint RPC.

**Comment by faboweb** [comment]
I am trying to use Keplr on a SDK 0.40 network. Signing on stargate is compatible to the old versions as far as I know. So launchpad should still work. But this check prevents the querying for the sequence.

**Comment by webmaster128** [comment]
Closing because the Stargate backends do not return an interface but the full account object, which looks different for every account type. See https://github.com/cosmos/cosmjs/issues/702#issuecomment-799599863.
