### ISSUE TITLE
Question: Is IBC transfer possible

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmjs#552]
Does the stargate package support the MsgTransfer? And is there some documentation on how to use the stargate package?

Cheers,
Fabo

**Comment by webmaster128** [comment]
It should, but this is untested. No documentation exists for that (yet). But the overall process would be

1. Use `QueryClient & IbcExtension` to access all the IBC queries as shown in https://github.com/CosmWasm/ibc-visualizer/pull/1, especially this file https://github.com/CosmWasm/ibc-visualizer/blob/initial-ibc-vis/src/contexts/ClientContext.tsx
2. Look at the decorator system to define messages in the caller code: https://github.com/cosmos/cosmjs/blob/v0.24.0-alpha.9/packages/proto-signing/src/decorator.spec.ts#L25-L48 and create a decorated class according to https://github.com/cosmos/cosmos-sdk/blob/v0.40.0-rc3/proto/ibc/applications/transfer/v1/tx.proto#L16-L40
3. Use [SigningStargateClient.signAndBroadcast](https://cosmos.github.io/cosmjs/latest/stargate/classes/signingstargateclient.html#signandbroadcast) to sign and broadcast the messages as [shown in those tests](https://github.com/cosmos/cosmjs/blob/v0.24.0-alpha.9/packages/stargate/src/signingstargateclient.spec.ts#L135-L202).

**Comment by webmaster128** [comment]
My previous answer is outdated, especially because it refers to protbuf type generation before we switched to ts-proto.

The current state is:
1. You can use code generation to generate custom message types as well as queries. This is documented here: https://github.com/cosmos/cosmjs/blob/main/packages/stargate/CUSTOM_PROTOBUF_CODECS.md
2. `MsgTransfer` is not part of CosmJS because we don't use it internally. This would change with #725

Both 1. and 2. are possible with CosmJS 0.24.x. Now when it comes to raw IBC queries and message types, [we added a lot of stuff](https://github.com/cosmos/cosmjs/pull/711) for the upcoming 0.25.x.

Closing this here. Let's follow up in more specific tickets. Thanks!
