### ISSUE TITLE
Split Tendermint client into Tendermint33Client and Tendermint34Client

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#642]
Creating a Tendermint client that makes the full Tendermint RPC API available to the user should be easy. Users need to do that to e.g. create custom quey clients.

Auto-detecting the Tendermint version of the backend does not work anymore starting with Tendermint 0.34. We should give it up. Also `Client` exposes and interface that tries to generalize between Tendermint 0.33 and Tendermint 0.34. If we split it into two clients, the interfaces can be more specific.

Right now, using the Tendermint client [looks like](
https://github.com/CosmWasm/ibc-visualizer/blob/55fe307/src/contexts/ClientContext.tsx)

```ts
import { adaptor34, Client as TendermintClient } from "@cosmjs/tendermint-rpc";

// ...

const tmClient = await TendermintClient.connect(config.rpcUrl, adaptor34);
```

which has a few flaws:

- `Client` is never a great name to import and always needs to be renamed. So it would be nice if we give it a useful name by default, even if slightly redundant with the package name
- `adaptor34` was designed to be private but was exposed later on. Not pretty to work with.
- The async in the constructor is only needed for auto-detection. It can probably be sync now.

Instead, this could look like

```ts
import { Tendermint34Client } from "@cosmjs/tendermint-rpc";

// ...

const tmClient = new Tendermint34Client(config.rpcUrl);
```

**Comment by ethanfrey** [comment]
Great idea. We can have different response values for them as well, rather than auto-converting.

0.33 can keep the present return values.

for 0.34, I would suggest importing the generated tendermint types: https://github.com/cosmos/cosmjs/tree/main/packages/stargate/src/codec/tendermint/types

They use protobuf internally and marshal to json for the rpc. There will need to be a bit of checks/conversion I think, especially things like oneof are different between go and js I think, but most of it is there. And returning these protobuf types makes us more future-compatible with 0.35 which plans a grpc interface.
