### ISSUE TITLE
Explore simulation for help in choosing gas limits

### ISSUE THREAD

**Issue by willclarktech** [cosmos/cosmjs#828]
After https://github.com/cosmos/cosmjs/issues/827

**Comment by ethanfrey** [comment]
There is an abci query endpoint called /simulate, which will run delivertx on a temporary copy of the state (which will never be committed). The result informs if the tx will (likely) succeed and how much gas it used.

This estimate is often off a bit due to caching, but multiplying by say 1.2 or 1.3 almost always is sufficient. It would be nice to easily expose this for any message type, like signAndBroadcast

**Comment by ethanfrey** [comment]
This is needed for https://github.com/confio/ts-relayer/issues/198

Please ping on that issue when this is completed. (No rush on it, just don't want to forget this) It also provides a concrete use case.
