### ISSUE TITLE
Address to public key?

### ISSUE THREAD

**Issue by AlexBHarley** [cosmos/cosmjs#889]
Given an address - `cosmos....` - can I get the corresponding public key for it?

I see there's a `pubkeyToAddress` method, in Ethereum land I'm used to the reverse function, would be super helpful in the context of WalletConnect!

**Comment by webmaster128** [comment]
The reverse calculation (address to pubkey) is not possible, neither in Cosmos nor in Ethereum. What you can do is ask the chain if it stores the public key for a given address. If the address has signed transactions before, this gives you a public key on Cosmos. In Ethereum this is even harder because no public keys are stored. You need to generate them by ECDSA pubkey recovery from message+signature of a transaction.

So I am wondering what Ethereum functionality you refer to and why it sounds so simple. Maybe we are talking about different things.

**Comment by AlexBHarley** [comment]
This was definitely a late night comment 😅 I appreciate the response. Doing an ecrecover was exactly what I was thinking of...

**Comment by ashraful1980** [comment]
Is it possible corresponding public key from the bitcoin address?
