### ISSUE TITLE
Generate and store salt

### ISSUE THREAD

**Issue by shapkarin** [cosmos/cosmjs#903]
Hello. It there any way to make salt configurable? 

https://github.com/cosmos/cosmjs/blob/f198f0acc425051f0ebd71489d993d7851b48475/packages/proto-signing/src/wallet.ts#L15

I found a way to replace that file. And put salt to the env variable:
```js
new webpack.NormalModuleReplacementPlugin(
  new RegExp('@cosmjs/proto-signing/build/wallet.js'),
  path.resolve(
    __dirname,
    'replaced/wallet.js'
  )
)
```
Of course someone can find the value in a builded js, but it looks harder.

**Comment by webmaster128** [comment]
> Hello. It there any way to make salt configurable?

Heyho! Why do you want to do that? I'd be curious about a detailed motivation and usecase description. If it makes sense to do, it should be trivial to make it configurable through proper APIs.

> Of course someone can find the value in a builded js, but it looks harder.

Are you sure you're on the right path here? The salt is not a secret value. It's public and that's perfectly fine. It just makes rainbow attacks harder.

**Comment by shapkarin** [comment]
While wallet development, I decided that If `It just makes rainbow attacks harder`, why not make it a bit more harder with "hidden" salt from env variable.

**Comment by webmaster128** [comment]
Okay, so one scenario could be this: All CosmJS users use the same salt. One can come up with a rainbow table of passwords that are all hashed with one salt in order to attack CosmJS users. Now what you can do is override the salt in each application. Still no need for env variables and hiding. Then you need application specific tables instead of lib specific tables, making them much harder to generate or less attractive.

I'm unsure if this is worth it. Changing the argon 2 parameters should be enough to ger unique hashes and at the same time tune the difficulty of the KDF. Then if you push this computation to a WebWorker to not freeze the UI you can go really high with your params. Development effort is much more worth there. Also this heavily reduces the risk that an encrypted wallet cannot be decrypted anymore because you remain compatible with standard CosmJS tooling.

**Comment by shapkarin** [comment]
> Then you need application specific tables instead of lib specific tables, making them much harder to generate or less attractive.

That was the goal. Instead of `lib specific tables` has different `application specific tables` so one table can't be used to any app.

**Comment by webmaster128** [comment]
Yeah. This can be done and there is nothing wrong with it. But I highly recommend not making this a priority and don't implement costy and risky hacks for it.

I leave this ticket open to make the salt configurable. This is easy to implement.

**Comment by webmaster128** [comment]
I wonder if we could just store the salt together with all other argon2 options. The options need to be read anyways before the decryption. Then we can automatically generate a new salt for every encryption.

**Comment by shapkarin** [comment]
Agree, it could be an option with default value "The CosmJS salt.".

**Comment by shapkarin** [comment]
@webmaster128 I don't have problems to provide a new `PR`. But not right now or today. Maybe tomorrow's evening.

**Comment by webmaster128** [comment]
Alright, go ahead. No rush. I'll look at it then.

**Comment by shapkarin** [comment]
will try to add *.spec.ts, feel free to add yours if PR will not include it.

**Comment by webmaster128** [comment]
Looking at the new title, I just want to make sure we are on the same page:
- Salt is randomly generated, not configured at encryption time
- It is stored together with the other Argon2 options in a field `salt?: string` (hex or base64 encoded)
- When decrypting, the salt is used. When non-existent, the default salt is used.

This means we don't have any additional work for the user of the library – just upgrade.

**Comment by shapkarin** [comment]
Thanks. Got that. To create random salt for each encryption and store it next to a cipher.

**Comment by webmaster128** [comment]
The steps are done as follows:
1. User provides password string, possibly low entropy
2. The KDF turns this string into a byte series using a hard to bruteforce algorithm that is configurable. This KDF may or may not have a salt. A output length for the encryption key is configured.
3. The encryption is performed using the encryption key from 2.

Step 3 does not know where the encryption key comes from. It does not know which KDF is used and what a KDF even is. It does not know what a salt is because encryption has no salt.

So the salt clearly belongs to the KDF step. And it is algorithm specific. For this reason I would pout it in `kdf.params` and `Argon2idOptions`.

**Comment by shapkarin** [comment]
What do you think about to code that? Does't looks like I have a lot of time for that. In any case will back to it this week, please mark this issue in a commit #903

**Comment by shapkarin** [comment]
@webmaster128 hello, can you please closer describe the problem? I will try to find some time for the help.

**Comment by shapkarin** [comment]
@webmaster128 hello I will try to prepare the PR. 
I guess that I can just use something like:

```js
import { Random } from '@cosmjs/crypto'

const salt = Random.getBytes(16);
```

**Comment by shapkarin** [comment]
@webmaster128 it may be like that https://github.com/cosmos/cosmjs/pull/906/commits/663d39c7bb645a8a420ef8e2c7444ccf68e8d718

But next I should return the salt itself with
https://github.com/cosmos/cosmjs/blob/663d39c7bb645a8a420ef8e2c7444ccf68e8d718/packages/crypto/src/libsodium.ts#L46 and it use `libsodium-wrappers` package

**Comment by shapkarin** [comment]
I'm not completely sure buy maybe `sodium.randombytes_buf(16)` 
Or even `crypto_pwhash` can be replaced with `sodium.crypto_pwhash_str` - that already generate random salt and also use Argon2ID.
But of course crypto_pwhash adds more control.

**Comment by shapkarin** [comment]
@webmaster128 also maybe `sodium.randombytes_buf(16)` can be used instead of `Random.getBytes(16)`.

Not sure but maybe even `sodium.crypto_pwhash` can be replaced with `sodium.crypto_pwhash_str` - it already generate random salt and also use Argon2ID.
But of course `crypto_pwhash` gives more control and the returns not just a string.

**Comment by shapkarin** [comment]
@webmaster128 hello. random salt is already used in the wallet module
https://github.com/cosmos/cosmjs/blob/486ab65ed9d0d935c3f15760e64cbf707a85a1b4/packages/proto-signing/src/wallet.ts#L55-L72, but not in the `directsecp256k1hdwallet` https://github.com/cosmos/cosmjs/blob/fcf01d4b09ed2cda3edff5e5d75f3670d22ddd77/packages/proto-signing/src/directsecp256k1hdwallet.ts#L294-L298
https://github.com/cosmos/cosmjs/blob/fcf01d4b09ed2cda3edff5e5d75f3670d22ddd77/packages/proto-signing/src/wallet.ts#L26-L36

**Comment by webmaster128** [comment]
Wallet encryption might be removed entirely from CosmJS. If you use this in production code, please let us know in #1479.
