### ISSUE TITLE
Core API queries are missing

### ISSUE THREAD

**Issue by JoeKash** [cosmos/cosmjs#926]
It seem like a lot of queries like slashing are missing from the API.

I can see this PR  for adding them in - 
https://github.com/cosmos/cosmjs/pull/286

But it seem like this changes never actually made it in the library

**Comment by webmaster128** [comment]
The linked PR adds queries to the sdk38 package, which is shoort for Cosmos SDK 0.38. This was later renamed to launchpad and the functionality is there for Launchpad chains. It is very well possible the queries are missing for the stargate package.

Could you open a ticket with the specific queries that are missing? This makes it much easier for us to break it down and get it done. Otherwise we don't really see what people are missing.

Closing here as unspecific. Please follow up with new tickets.

**Comment by JoeKash** [comment]
I've only noticed the slashing for now but I assume there are more.

I'll open a ticket for the slashing for now
