### ISSUE TITLE
Publish as a Universal Module Definition?

### ISSUE THREAD

**Issue by maxcountryman** [cosmos/cosmjs#998]
Hi folks, curious if it's been discussed if this might be possible? This is something that similar libraries like `terra.js` do; that enables things like this:

```html
<script
  crossorigin
  src="https://unpkg.com/@terra-money/terra.js/dist/bundle.js"
></script>
```

This means that I don't need a build pipeline to consume the library, which in my specific case would be quite nice because I'm hooking into libraries like this via a wasm runtime.

**Comment by ethanfrey** [comment]
> I'm hooking into libraries like this via a wasm runtime.

?? 

If you are writing a wasm runtime for the client, maybe you want to [look at cosmrs](https://github.com/cosmos/cosmos-rust)

**Comment by maxcountryman** [comment]
cosmrs cannot compile to a wasm target because it depends on crates like tendermint. Yes, I would generally prefer this altho that isn't the complete picture.

Curious why we wouldn't build a udm for cosmjs, regardless of my particular use case?

**Comment by maxcountryman** [comment]
There's really no need for the aggressive tone. No one is trying to say this is easy, the question is would it be useful and so should we. 

There's value in giving users the option to avoid a build JavaScript pipeline like Terra does and that's no doubt why they offer it for their tool chain. 

UDM isn't just an idea, it's targetable with a tool like webpack. Each package can be configured to build a UDM if desired (it can be as simple as adding a few config lines to a webpack config, for example). It might not be as difficult as it might at first sound.

**Comment by webmaster128** [comment]
Sorry for the tone. But JS module fragmentation and all the hackery around it stresses me. Also people implying things are doable or easy just because they work elsewhere without being aware of the complexity of CosmJS makes me annoyed. And you asked why we wouldn't build it, not if it would add value. Yes, it would add value.

I fully agree that CosmJS is hard to access. It's poorly documented and too complex for most newcomers. This is because it is very powerful and serves many different very advanced use cases. It has completely different limitations and trade-offs then a client library that only serves one chain.

I think the best way to make progress if you really want this is create a new project that pulls in all the @cosmjs/* dependencies you care about and re-export them. This way you can decide which functionality you want to have and which you leave out. Then you end up with a single entry point to the wrapper library. This can be bundled and expose a UMD interface. There are probably other users that would appreciate this (see e.g. https://github.com/cosmos/cosmjs/issues/921).

**Comment by maxcountryman** [comment]
> Also people implying things are doable or easy just because they work elsewhere without being aware of the complexity of CosmJS makes me annoyed.

I am aware of the complexity. However, there are plenty of JavaScript libraries that are arguably far more complex and are still able to achieve this. It'd be interesting to really interrogate why cosmjs would be an exception, but if you all aren't interested in that I won't pursue it further.

Please understand, I'm not saying it's easy, but I don't think it's fair to say this set of packages is somehow so complex it's simply not possible (if there's some technical reason for this I'm not aware of, that's fair, but it would be surprising given I can just re-export arbitrary cosmjs packages and it "just works"). For example, I mentioned one path forward: it may be possible to configure each package to build its own UMD, this fits a common pattern a la the vector of unpkg.

> I think the best way to make progress if you really want this is create a new project that pulls in all the @cosmjs/* dependencies you care about and re-export them.

Fair enough. This is what I'm currently doing, so I'll continue with that.

If cosmrs were made to be targetable for wasm runtimes I would pursue that instead, but I think that's likely very difficult given e.g. the tendermint crate specifically. (You can probably make it work for a subset of features, but I need to be able to leverage RPC etc, so I believe that means there's no path forward there.)

Re tone, I frankly have serious reservations about pursuing Cosmos if this is how folks are building the dev community. This is hard work, yes. (And can I just say, amazing work; very well done!) But if we dismiss every hard problem as being too hard and therefore not worth the effort plus react as such with folks then it's hard to see how this leads to the cultivation of a thriving dev community that builds meaningful traction. (Just to be clear, I think it's valid to say here this too far outside the scope of what the library is trying to do, I just would have preferred if that message had been delivered a little differently.)

**Comment by webmaster128** [comment]
I see your concern and am sorry for the negative experience.

But I'm not building a dev community and don't evangelize. I'm not claiming anyone should use any of the dozens of Cosmos based chains this library is compatible with. My job is not to make everyone happy for every possible use case. CosmJS is about building a rock solid foundation of core low level tech. If that means there should be multiple layers between the core library and a web app, fine. CosmJS is a bad entry point for newcomers to the wider Cosmos ecosystem and unfortunately I don't know a better one right now. I hear roumors that there are people working on that. But I don't actually know as there are dozens of independent organizations working on the inner circle of Cosmos.

I dismiss it because it is a combination of 1. being hard, 2. not a problem for most web users I encountered who are having their build system anyways, 3. the proposed solution is obsolete once we figure out how es6 libraries can be written in a way they work in both node and web at the same time.
